#!/bin/bash
#This script must be preprocessed before use and any identifiers prefixed and
#postfixed with __ must be replaced.
. ./hooks/env

#Reset the respository since it's not a bare git repo.
reset-head.sh $1

#Call the similarity checker
similarity-check.sh

#For now always indicate successs, this should be updated later
exit 0
