#!/usr/bin/php
<?php
include './hooks/environment.php';
include 'hooks.php';

return postUpdate(
                    [
                    'assignmentId' => $ASSIGNMENT_ID,
                    'similarity' => $SIMILARITY_THRESHOLD,
                    'studentId' => $STUDENT_ID,
                    'assignmentPath' => $ASSIGNMENT_DIR,
                    ]
                );
?>
